### ISSUE TITLE
sessionのsecretについて

### ISSUE THREAD

**Issue by mosmos21** [ryusuke920/AtCoderList#1]
サーバーアプリケーション内でのsession secretの指定がコード上に記載されていますが、この文字列は流出するとセッション情報の偽造が可能になる危険性があります。secretに指定する文字列はランダムな文字列(一般に30文字以上程度)であることが好ましいため、早急に修正を行った方が良いです。
https://github.com/ryusuke920/AtCoderList/blob/main/app.js#L32

対応方法
- 本番用のsecretは環境変数として指定します
  - herokuを利用しているようですので [こちら](https://devcenter.heroku.com/articles/config-vars) が参考になります
- コード上は環境変数を利用するように修正します(`SESSION_SECRET`の部分は環境変数で指定した名前です)

```javascript
secret: process.env.SESSION_SECRET || 'my_secret_key'
```

**Comment by ryusuke920** [comment]
上記のコードを追加して解決しました。
